/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Insets;
import javax.swing.BorderFactory;
import javax.swing.JButton;
import javax.swing.JFrame;
import static javax.swing.JFrame.EXIT_ON_CLOSE;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.UIManager;

/**
 *
 * @author Riccardo Petrone
 */
public class Login extends javax.swing.JFrame {

    private JTextField txtUsername = new JTextField(15);
    private JPasswordField txtPassword = new JPasswordField(15);
    private JButton btnLogin = new JButton("Login");

    /**
     * Creates new form Login
     */
    public Login() {

        // ===== FINESTRA =====
        setTitle("Login - Gestione Magazzino");
        setSize(450, 350);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setResizable(false);

        Color sfondo = new Color(25, 28, 42);
        Color pannello = new Color(40, 44, 62);
        Color blu = new Color(99, 132, 255);

        getContentPane().setBackground(sfondo);

        // ===== PANEL CENTRALE =====
        JPanel panel = new JPanel(new GridLayout(4, 2, 10, 10));
        panel.setBackground(pannello);
        panel.setBorder(BorderFactory.createEmptyBorder(30, 30, 30, 30));

        // ===== TITOLO =====
        JLabel lblTitolo = new JLabel("GESTIONE MAGAZZINO");
        lblTitolo.setForeground(blu);
        lblTitolo.setFont(new Font("SansSerif", Font.BOLD, 18));

        // ===== LABEL =====
        JLabel lblUsername = new JLabel("Username:");
        JLabel lblPassword = new JLabel("Password:");

        lblUsername.setForeground(Color.WHITE);
        lblPassword.setForeground(Color.WHITE);

        // ===== CAMPI TESTO =====
        txtUsername = new JTextField();
        txtPassword = new JPasswordField();

        txtUsername.setBackground(new Color(55, 60, 82));
        txtPassword.setBackground(new Color(55, 60, 82));

        txtUsername.setForeground(Color.WHITE);
        txtPassword.setForeground(Color.WHITE);

        // ===== BOTTONE =====
        btnLogin = new JButton("Accedi");

        btnLogin.setBackground(blu);
        btnLogin.setForeground(Color.WHITE);
        btnLogin.setFocusPainted(false);
        btnLogin.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // ===== AGGIUNTA COMPONENTI =====
        panel.add(lblUsername);
        panel.add(txtUsername);

        panel.add(lblPassword);
        panel.add(txtPassword);

        panel.add(new JLabel());
        panel.add(btnLogin);

        // ===== WRAPPER =====
        JPanel wrapper = new JPanel(new BorderLayout());
        wrapper.setBackground(sfondo);

        wrapper.add(lblTitolo, BorderLayout.NORTH);
        wrapper.add(panel, BorderLayout.CENTER);

        lblTitolo.setHorizontalAlignment(SwingConstants.CENTER);

        add(wrapper);

        // ===== EVENTO LOGIN =====
        btnLogin.addActionListener(e -> {

            String username = txtUsername.getText();
            String password = new String(txtPassword.getPassword());

            if (username.equals("progetto") && password.equals("Uda")) {

                JOptionPane.showMessageDialog(this, "Login effettuato!");

                new Main().setVisible(true);
                dispose();

            } else {

                JOptionPane.showMessageDialog(this, "Credenziali errate!");

            }
        });

        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        new Login();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
