/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.HeadlessException;
import java.awt.TextArea;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.Product;
import model.csvReader;
import java.io.FileWriter;
import javax.swing.JMenuItem;

/**
 *
 * @author petroner
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();

        JMenuItem infoItem = new javax.swing.JMenuItem("Info");
        About.add(infoItem);

        infoItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JOptionPane.showMessageDialog(null,
                        "Gestione Magazzino v1.0\n"
                        + "Autori: Riccardo Petrone, Giuseppe Romanucci\n"
                        + "Anno scolastico: 2025/2026\n"
                        + "Istituto Blaise Pascal",
                        "About",
                        JOptionPane.INFORMATION_MESSAGE);
            }
        });
        
        scrollPane.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollPane = new javax.swing.JScrollPane();
        tblProducts = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        File = new javax.swing.JMenu();
        Open = new javax.swing.JMenuItem();
        Save = new javax.swing.JMenuItem();
        SaveWIthName = new javax.swing.JMenuItem();
        Exit = new javax.swing.JMenuItem();
        Edit = new javax.swing.JMenu();
        About = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scrollPane.setMaximumSize(null);
        scrollPane.setMinimumSize(null);

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblProducts.setPreferredSize(null);
        scrollPane.setViewportView(tblProducts);

        getContentPane().add(scrollPane, java.awt.BorderLayout.CENTER);

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N

        File.setText("File");

        Open.setText("Open");
        Open.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpenActionPerformed(evt);
            }
        });
        File.add(Open);

        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });
        File.add(Save);

        SaveWIthName.setText("Save WIth Name");
        SaveWIthName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveWIthNameActionPerformed(evt);
            }
        });
        File.add(SaveWIthName);

        Exit.setText("Exit");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        File.add(Exit);

        jMenuBar1.add(File);

        Edit.setText("Edit");
        jMenuBar1.add(Edit);

        About.setText("About");
        jMenuBar1.add(About);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpenActionPerformed
        openFile();
    }//GEN-LAST:event_OpenActionPerformed

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        saveFile();
    }//GEN-LAST:event_SaveActionPerformed

    private void SaveWIthNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveWIthNameActionPerformed
        saveFileAs();
    }//GEN-LAST:event_SaveWIthNameActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        exitApp();
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    private File currentFile;
    ArrayList<Product> products = null;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu About;
    private javax.swing.JMenu Edit;
    private javax.swing.JMenuItem Exit;
    private javax.swing.JMenu File;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem Save;
    private javax.swing.JMenuItem SaveWIthName;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JTable tblProducts;
    // End of variables declaration//GEN-END:variables
 
    private void showProducts() {
        if (products == null || products.isEmpty()) {
            return;
        }
        
        scrollPane.setVisible(true); // fa riapparire la tabella
        
        String[] colonne = {"ID", "Name", "Category", "Brand", "Price", "Quantity", "Supplier"};
        Object[][] dati = new Object[products.size()][7];

        for (int i = 0; i < products.size(); i++) {
            Product p = products.get(i);
            dati[i][0] = p.getId();
            dati[i][1] = p.getName();
            dati[i][2] = p.getCategory();
            dati[i][3] = p.getBrand();
            dati[i][4] = p.getPrice();
            dati[i][5] = p.getQuantity();
            dati[i][6] = p.getSupplier();
        }

        tblProducts.setModel(new javax.swing.table.DefaultTableModel(dati, colonne));
        pack();
        revalidate();  
        repaint(); 
    }

    private void openFile() {
        JFileChooser chooser = new JFileChooser();
        if (chooser.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            
            // prendo il file scelto dall'utente
            currentFile = chooser.getSelectedFile();

            // creo il reader passandogli il percorso del file
            csvReader reader = new csvReader();

            // leggo il CSV e salvo tutto nell'array
            products = reader.readFile(currentFile.getAbsolutePath());

            JOptionPane.showMessageDialog(this, "Caricati " + products.size() + " prodotti");
            showProducts();
            
        }
    }

    private void saveFile() {
        if (currentFile == null) {
            JOptionPane.showMessageDialog(this, "No files open!");
            return;
        }

        try {
            FileWriter fw = new FileWriter(currentFile);
            
            fw.write("ID,Name,Category,Brand,Price,Quantity,Supplier\n");
            
            for (Product p : products) {
                fw.write(p.toString() + "\n");
            }

            fw.close();
            JOptionPane.showMessageDialog(this, "file saved!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void saveFileAs() {
        JFileChooser chooser = new JFileChooser();

        if (chooser.showSaveDialog(this) == JFileChooser.APPROVE_OPTION) {
            currentFile = chooser.getSelectedFile();
            saveFile();
        }
    }

    private void exitApp() {
        int risposta = JOptionPane.showConfirmDialog(this, "Are you sure you want to go out?", "Exit", JOptionPane.YES_NO_OPTION);

        if (risposta == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }
}
